apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: quarkus-example
spec:
  type: brokered
  plan: brokered-single-broker
  endpoints:
    - name: messaging
      service: messaging
      cert:
        provider: openshift
      exports:
        - kind: ConfigMap
          name: quarkus-config
