apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-binding-quarkus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-quarkus
subjects:
- kind: ServiceAccount
  name: address-space-controller
  namespace: enmasse-infra
