spec:
  template:
    spec:
      containers:
        - env:
            - name: AMQP_HOST
              valueFrom:
                configMapKeyRef:
                  name: quarkus-config
                  key: service.host
            - name: AMQP_PORT
              valueFrom:
                configMapKeyRef:
                  name: quarkus-config
                  key: service.port.amqp
