apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: quarkus-example.app
spec:
  username: app
  authentication:
    type: serviceaccount
  authorization:
    - operations: ["recv"]
      addresses: ["events"]
    - operations: ["send"]
      addresses: ["control"]
