apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: vertx-example.client
spec:
  username: client
  authentication:
    type: password
    password: dGVzdA==
  authorization:
    - operations: ["send", "recv"]
      addresses: ["myqueue"]
