apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: quarkus-example-client
  name: quarkus-example-client
spec:
  output:
    to:
      kind: ImageStreamTag
      name: quarkus-example-client:latest
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: src/main/docker/Dockerfile
    type: Docker
