apiVersion: v1
kind: DeploymentConfig
metadata:
  name: quarkus-example-client
  labels:
    app: quarkus-example-client
spec:
  replicas: 1
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "quarkus-example-client"
        from:
          kind: "ImageStreamTag"
          name: "quarkus-example-client:latest"
  template:
    metadata:
      labels:
        app: quarkus-example-client
        application: demo

    spec:
      containers:
        - name: quarkus-example-client
          image: quarkus-example-client:latest
          env:
            - name: MESSAGING_HOST
              valueFrom:
                configMapKeyRef:
                  name: messaging-config
                  key: service.host
            - name: MESSAGING_PORT
              valueFrom:
                configMapKeyRef:
                  name: messaging-config
                  key: service.port.amqp
