apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: jms-example
spec:
  type: brokered
  plan: brokered-single-broker
  endpoints:
    - name: messaging
      service: messaging
      cert:
        provider: openshift
    - name: console
      service: console
      expose:
        type: route
        routeTlsTermination: reencrypt
        routeServicePort: https
