apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: jms-example
spec:
  type: brokered
  plan: brokered-single-broker
  endpoints:
    - name: messaging
      service: messaging
      exports:
      - kind: ConfigMap
        name: messaging-config
      cert:
        provider: openshift
