apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: jms-example.client
spec:
  username: system:serviceaccount:myapp:default
  authentication:
    type: serviceaccount
  authorization:
    - operations: ["send", "recv"]
      addresses: ["myqueue"]
