apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: microprofile-example
spec:
  type: standard
  plan: standard-small
  endpoints:
    - name: messaging
      service: messaging
      cert:
        provider: openshift
      exports:
        - kind: ConfigMap
          name: microprofile-config
